### ISSUE TITLE
Login with Github fails when name is null

### ISSUE THREAD

**Issue by nilloq** [Barbapapazes/gavarnie#22]
User name is not mandatory in a Github profile, so in Github OAuth response the "name" field can be null.
In that case the createUser fails with a 500 error : "D1_ERROR: NOT NULL constraint failed: users.name: SQLITE_CONSTRAINT"

My suggestion would be to use github login in user.name when github name is not defined.

**Comment by Barbapapazes** [comment]
Hey 👋,

Thanks for noticing this!
