### ISSUE TITLE
Bug: unlinking all oauth providers breaks users login

### ISSUE THREAD

**Issue by GreenmeisterDavid** [Barbapapazes/gavarnie#28]
Currently when a user unlinks all oauth providers they cannot login anymore. This is expected, but if they try to login with a new/different provider that has the same email address, the user will get an error along the lines of _'an account already exists with this email, login to that one and link it this provider'_. This blocks them from logging in and renders the existing account inaccessible. 

I suggest adding a simple check, both frontend and backend, before removing a provider. If that provider is the users' only method of logging in (the only auth provider linked), display an error. 

Shall I create a pull request for this or is another way of handling this preferred? 

💚

**Comment by Barbapapazes** [comment]
How does this happen?

There is already a security to avoid the user to remove all providers

<img width="428" alt="Screenshot 2024-10-14 at 18 05 06" src="https://github.com/user-attachments/assets/1ae495d3-d452-46e6-9d3c-e92856472e40">

https://github.com/Barbapapazes/gavarnie/blob/main/server/api/me/providers/%5BproviderName%5D.delete.ts#L9

**Comment by GreenmeisterDavid** [comment]
My bad, I forgot to add 'google' in the provider checks in my PR to add it, just committed a fix for it here; https://github.com/Barbapapazes/gavarnie/pull/27 . 


Maybe we can centralize providers somewhat more to make it easier to add/remove them? 

Closing this as its not relevant here.
