### ISSUE TITLE
`@nuxt/ui-pro` is missing in `package.json`

### ISSUE THREAD

**Issue by andrzejrumak** [Barbapapazes/gavarnie#6]
Hello,
 there isn't @nuxt/ui-pro in dependencies and it gives errors at the begining after pnpm run dev

**Comment by Barbapapazes** [comment]
Hello,

Indeed, I will add it.

**Comment by andrzejrumak** [comment]
Hi, sorry to continue this issue but we do not need to install @nuxt/ui yourself as it's already a dependency of @nuxt/ui-pro. 
https://ui.nuxt.com/pro/getting-started/installation

**Comment by Barbapapazes** [comment]
Hey,

Thanks for reporting this! I open a new issue.
